/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "SST.h"
#include "LED_AO.h"
#include "stm32f3xx.h"

#define BSP_TICKS_PER_SEC 1000U

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void DBC_fault_handler(char const * const module, int const label) {}
/* SST callbacks ===========================================================*/
void SST_onStart(void) {
   SystemCoreClockUpdate();

   /* set up the SysTick timer to fire at BSP_TICKS_PER_SEC rate */
   SysTick_Config((SystemCoreClock / BSP_TICKS_PER_SEC) + 1U);

   /* set priorities of ISRs used in the system */
   NVIC_SetPriority(SysTick_IRQn, 0U);
   /* ... */
}
/*..........................................................................*/
void SST_onIdle(void) {
#ifdef NDEBUG
   __WFI(); /* Wait-For-Interrupt */
#endif
}

int main(void)
{
	SST_init();
	LEDAO_Initialize();
    /* Loop forever */
	for(;;);
}
